### ISSUE TITLE
DraggableGridView won't inflate in layout

### ISSUE THREAD

**Issue by RyanGlScott** [thquinn/DraggableGridView#2]
I'm attempting to use DraggableGridView in a Dialog in my project. I've done everything that the README instructs me to do, namely:
- I added DraggableGridView.jar to /libs and added it to my build path
- I added <com.animoto.android.views.DraggableGridView ... /> to my XML layout
- I imported "import com.animoto.android.views.DraggableGridView;" and "import com.animoto.android.views.OnRearrangeListener;" to the corresponding Java file

However, when I try to use DraggableGridView in my project, I get the following errors:

<pre>
04-07 13:52:58.186: E/AndroidRuntime(12849): FATAL EXCEPTION: main
04-07 13:52:58.186: E/AndroidRuntime(12849): android.view.InflateException: Binary XML file line #8: Error inflating class com.animoto.android.views.DraggableGridView
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.view.LayoutInflater.createView(LayoutInflater.java:613)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at com.kufpg.androidhermit.dialog.ConsoleEntryRearrangeDialog.onCreateView(ConsoleEntryRearrangeDialog.java:56)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.Fragment.performCreateView(Fragment.java:1695)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:885)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1057)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.BackStackRecord.run(BackStackRecord.java:682)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1435)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:441)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.os.Handler.handleCallback(Handler.java:725)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.os.Handler.dispatchMessage(Handler.java:92)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.os.Looper.loop(Looper.java:137)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.app.ActivityThread.main(ActivityThread.java:5041)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at java.lang.reflect.Method.invokeNative(Native Method)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at java.lang.reflect.Method.invoke(Method.java:511)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at dalvik.system.NativeStart.main(Native Method)
04-07 13:52:58.186: E/AndroidRuntime(12849): Caused by: java.lang.reflect.InvocationTargetException
04-07 13:52:58.186: E/AndroidRuntime(12849):    at java.lang.reflect.Constructor.constructNative(Native Method)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
04-07 13:52:58.186: E/AndroidRuntime(12849):    at android.view.LayoutInflater.createView(LayoutInflater.java:587)
04-07 13:52:58.186: E/AndroidRuntime(12849):    ... 20 more
04-07 13:52:58.186: E/AndroidRuntime(12849): Caused by: java.lang.ClassCastException: android.view.ContextThemeWrapper cannot be cast to android.app.Activity
04-07 13:52:58.186: E/AndroidRuntime(12849):    at com.animoto.android.views.DraggableGridView.<init>(DraggableGridView.java:56)
04-07 13:52:58.186: E/AndroidRuntime(12849):    ... 23 more
</pre>

...which is strange, because the exact same DraggableGridView code works in the sample activity. For reference, here is my XML file (console_entry_rearrange_dialog.xml):

``` xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="@dimen/entry_padding" >

    <com.animoto.android.views.DraggableGridView
        android:id="@+id/console_entry_rearrange_dialog_contents"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_alignParentLeft="true"
        android:layout_alignParentTop="true" >
    </com.animoto.android.views.DraggableGridView>

    <Button
        android:id="@+id/console_entry_rearrange_done"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/console_entry_rearrange_dialog_contents"
        android:text="Do cool stuff" />

</RelativeLayout>
```

and here is the file in which DraggableGridView is used (ConsoleEntryRearrangeDialog.java):

``` java
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import com.animoto.android.views.DraggableGridView;
import com.animoto.android.views.OnRearrangeListener;
import com.kufpg.androidhermit.R;
import com.kufpg.androidhermit.console.ConsoleActivity;

import android.app.DialogFragment;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Rect;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;

public class ConsoleEntryRearrangeDialog extends DialogFragment {

    private DraggableGridView mGridView;
    private Button mCoolStuffButton;
    private int mEntryNum;
    private String mEntryContents;
    private List<String> mSentence = new ArrayList<String>();
    private Random mRandom = new Random();

    public static ConsoleEntryRearrangeDialog newInstance(int entryNum, String entryContents) {
        ConsoleEntryRearrangeDialog cerd = new ConsoleEntryRearrangeDialog();

        Bundle args = new Bundle();
        args.putInt("entryNum", entryNum);
        args.putString("entryContents", entryContents);
        cerd.setArguments(args);

        return cerd;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mEntryNum = getArguments().getInt("entryNum");
        mEntryContents = getArguments().getString("entryContents");
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        super.onCreateView(inflater, container, savedInstanceState);
        View v = inflater.inflate(R.layout.console_entry_rearrange_dialog, container, false);
        setCancelable(false);

        getDialog().setTitle("Entry number " + String.valueOf(mEntryNum));
        mGridView = (DraggableGridView) v.findViewById(R.id.console_entry_rearrange_dialog_contents);
        for (String word : mEntryContents.split(ConsoleActivity.WHITESPACE)) {
            ImageView wordView = new ImageView(getActivity());
            wordView.setImageBitmap(getThumb(word));
            mGridView.addView(wordView);
            mSentence.add(word);
        }
        mGridView.setOnRearrangeListener(new OnRearrangeListener() {
            public void onRearrange(int oldIndex, int newIndex) {
                String word = mSentence.remove(oldIndex);
                if (oldIndex < newIndex)
                    mSentence.add(newIndex, word);
                else
                    mSentence.add(newIndex, word);
            }
        });

        mCoolStuffButton = (Button) v.findViewById(R.id.console_entry_rearrange_done);
        mCoolStuffButton.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(View v) {
                String newSentence = "";
                for (String word : mSentence) {
                    newSentence += word;
                }
                ((ConsoleActivity) getActivity()).showToast(newSentence);
            }
        });

        return v;
    }

    private Bitmap getThumb(String s) {
        Bitmap bmp = Bitmap.createBitmap(150, 150, Bitmap.Config.RGB_565);
        Canvas canvas = new Canvas(bmp);
        Paint paint = new Paint();

        paint.setColor(Color.rgb(mRandom.nextInt(128), mRandom.nextInt(128), mRandom.nextInt(128)));
        paint.setTextSize(24);
        paint.setFlags(Paint.ANTI_ALIAS_FLAG);
        canvas.drawRect(new Rect(0, 0, 150, 150), paint);
        paint.setColor(Color.WHITE);
        paint.setTextAlign(Paint.Align.CENTER);
        canvas.drawText(s, 75, 75, paint);

        return bmp;
    }


```

The error seems to trigger on View v = inflater.inflate(R.layout.console_entry_rearrange_dialog, container, false);.

**Comment by RyanGlScott** [comment]
Closing stale issue.
